# Matrix Arithmetic

In [1]:
import numpy as np

In [2]:
# create a (2x3) matrix
A = np.array([[1, 2, 3], [4, 5, 6]])

#print matrix
print(A)

[[1 2 3]
 [4 5 6]]


## Matrix Arithmetic
$C=A+B$
- Must have same dimensions

In [3]:
# define first matrix
A = np.array([
[1, 2, 3],
[4, 5, 6]])
print('Matrix A')
print(A)
print('\n')

# define second matrix
B = np.array([
[1, 2, 3],
[4, 5, 6]])
print('Matrix B')
print(B)
print('\n')

# add matrices
C = A + B
print('Matrices A + B')
print(C)

Matrix A
[[1 2 3]
 [4 5 6]]


Matrix B
[[1 2 3]
 [4 5 6]]


Matrices A + B
[[ 2  4  6]
 [ 8 10 12]]


## Matrix Subtraction
$C=A-B$

In [4]:
# define first matrix
A = np.array([
[1, 2, 3],
[4, 5, 6]])
print('Matrix A')
print(A)
print('\n')

# define second matrix
B = np.array([
[0.5, 2.7, 3],
[4.9, 3.2, 1]])
print('Matrix B')
print(B)
print('\n')

# subtract matrices
C = A - B
print('Matrices A - B')
print(C)

Matrix A
[[1 2 3]
 [4 5 6]]


Matrix B
[[0.5 2.7 3. ]
 [4.9 3.2 1. ]]


Matrices A - B
[[ 0.5 -0.7  0. ]
 [-0.9  1.8  5. ]]


## Matrix Multiplication (Hadamard Product)
$C = A ◦ B$

In [5]:
# define first matrix
A = np.array([
[1, 2, 3],
[4, 5, 6]])
print('Matrix A')
print(A)
print('\n')

# define second matrix
B = np.array([
[1, 2, 3],
[4, 5, 6]])
print('Matrix B')
print(B)
print('\n')

# multiply matrices
C = A * B
print('Matrices A * B')
print(C)

Matrix A
[[1 2 3]
 [4 5 6]]


Matrix B
[[1 2 3]
 [4 5 6]]


Matrices A * B
[[ 1  4  9]
 [16 25 36]]


## Matrix Division
$C = \frac {A}{B}$

In [6]:
# define first matrix
A = np.array([
[1, 2, 3],
[4, 5, 6]])
print('Matrix A')
print(A)
print('\n')

# define second matrix
B = np.array([
[1, 2, 3],
[4, 5, 6]])
print('Matrix B')
print(B)
print('\n')

# divide matrices
C = A / B
print('Matrices A * B')
print(C)

Matrix A
[[1 2 3]
 [4 5 6]]


Matrix B
[[1 2 3]
 [4 5 6]]


Matrices A * B
[[1. 1. 1.]
 [1. 1. 1.]]


## Matrix Dot Product
$C=AB$
- The number of columns in the first matrix (A) must equal the number of rows in the second matrix (B).

In [7]:
# define first matrix
A = np.array([
[1, 2],
[3, 4],
[5, 6]])
print('Matrix A')
print(A)
print('\n')

# define second matrix
B = np.array([
[1, 2],
[3, 4]])
print('Matrix A')
print(B)
print('\n')

# multiply matrices
C = A.dot(B)
print('Matrix A Dot B')
print(C)
print('\n')

# Alternatively multiply matrices with @ operator
D = A @ B
print('Alternate Method A@B ')
print(D)
print('\n')

Matrix A
[[1 2]
 [3 4]
 [5 6]]


Matrix A
[[1 2]
 [3 4]]


Matrix A Dot B
[[ 7 10]
 [15 22]
 [23 34]]


Alternate Method A@B 
[[ 7 10]
 [15 22]
 [23 34]]




## Matrix Vector Multiplication
$c=Av$
- The number of columns in the matrix must equal the number of items in the vector

In [8]:
# define first matrix
A = np.array([
[1, 2],
[3, 4],
[5, 6]])
print('Matrix A')
print(A)
print('\n')

# define vector
v = np.array([2,1])
print('Vector v')
print(v)
print('\n')

# multiply matrices
c = A.dot(v)
print('Matrix A Dot Vector v')
print(c)
print('\n')

Matrix A
[[1 2]
 [3 4]
 [5 6]]


Vector v
[2 1]


Matrix A Dot Vector v
[ 4 10 16]




## Matrix-Scalar Multiplication
$C = Ab$

In [9]:
# define first matrix
A = np.array([
[1, 2],
[3, 4],
[5, 6]])
print('Matrix A')
print(A)
print('\n')

# define scalar
b = 0.5
print('Scalar b')
print(b)
print('\n')

# multiply matrices
c = A*b
print('Matrix A * Scalar b')
print(c)
print('\n')

Matrix A
[[1 2]
 [3 4]
 [5 6]]


Scalar b
0.5


Matrix A * Scalar b
[[0.5 1. ]
 [1.5 2. ]
 [2.5 3. ]]


